[2025-03-24 18:52:31,289: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 18:52:32,067: INFO: main:  >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-03-24 18:52:32,068: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:52:32,069: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:52:32,069: INFO: common: created directory at: artifacts]
[2025-03-24 18:52:32,069: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-24 18:52:32,069: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 18:52:42,730: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 18:52:43,051: INFO: main:  >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2025-03-24 18:52:43,051: INFO: main: *******************]
[2025-03-24 18:52:43,051: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-24 18:52:43,052: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:52:43,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:52:43,053: INFO: common: created directory at: artifacts]
[2025-03-24 18:52:43,053: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "/Users/bardaanbudhathoki/Desktop/Kidney_Disease_Detection_Using_MLflow_DVC/main.py", line 27, in <module>
    prepare_base_model.main()
  File "/Users/bardaanbudhathoki/Desktop/Kidney_Disease_Detection_Using_MLflow_DVC/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2025-03-24 18:53:53,764: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 18:53:54,486: INFO: main:  >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-03-24 18:53:54,487: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:53:54,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:53:54,487: INFO: common: created directory at: artifacts]
[2025-03-24 18:53:54,487: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-24 18:53:54,487: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 18:54:01,624: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 18:54:01,925: INFO: main:  >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2025-03-24 18:54:01,925: INFO: main: *******************]
[2025-03-24 18:54:01,925: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-24 18:54:01,926: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:54:01,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:54:01,926: INFO: common: created directory at: artifacts]
[2025-03-24 18:54:01,926: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-24 18:54:02,192: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-24 18:54:02,233: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 18:54:02,234: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 18:54:02,269: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-24 18:54:02,269: INFO: main: *******************]
[2025-03-24 18:54:02,269: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-24 18:54:02,270: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:54:02,270: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:54:02,270: INFO: common: created directory at: artifacts]
[2025-03-24 18:54:02,270: INFO: common: created directory at: artifacts/training]
[2025-03-24 18:55:19,715: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-24 18:55:19,716: INFO: main: *******************]
[2025-03-24 18:55:19,716: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<]
[2025-03-24 18:55:19,717: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 18:55:19,718: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 18:55:19,718: INFO: common: created directory at: artifacts]
[2025-03-24 18:55:32,703: INFO: common: json file saved at: scores.json]
[2025-03-24 18:55:32,713: ERROR: main: [Errno 8] nodename nor servname provided, or not known]
Traceback (most recent call last):
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_transports/default.py", line 250, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    raise exc
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bardaanbudhathoki/Desktop/Kidney_Disease_Detection_Using_MLflow_DVC/main.py", line 51, in <module>
    obj.main()
  File "/Users/bardaanbudhathoki/Desktop/Kidney_Disease_Detection_Using_MLflow_DVC/src/cnnClassifier/pipeline/stage_04_model_evaluation_with_mlflow.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/Users/bardaanbudhathoki/Desktop/Kidney_Disease_Detection_Using_MLflow_DVC/src/cnnClassifier/components/model_evaluation_mlflow.py", line 58, in log_into_mlflow
    dagshub.init(repo_owner='NiteshNepal', repo_name='Kidney_Disease_Detection_Using_MLflow_DVC', mlflow=True)
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/common/init.py", line 86, in init
    repo_api = RepoAPI(f"{repo_owner}/{repo_name}", host=host)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/common/api/repo.py", line 78, in __init__
    self.auth = dagshub.auth.get_authenticator(host=host)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/auth/tokens.py", line 374, in get_authenticator
    return _get_token_storage(**kwargs).get_authenticator(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/auth/tokens.py", line 122, in get_authenticator
    token = self.get_token_object(host, fail_if_no_token, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/auth/tokens.py", line 165, in get_token_object
    user = TokenStorage.get_username_of_token(token, host)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/auth/tokens.py", line 239, in get_username_of_token
    resp = http_request("GET", check_url, auth=auth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/dagshub/common/helpers.py", line 60, in http_request
    return httpx.request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_api.py", line 109, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_client.py", line 825, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_client.py", line 1014, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_transports/default.py", line 249, in handle_request
    with map_httpcore_exceptions():
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/bardaanbudhathoki/miniconda3/envs/kidney_new/lib/python3.11/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
[2025-03-24 19:12:11,882: INFO: stage_01_data_ingestion:  >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-03-24 19:12:11,882: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:12:11,883: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:12:11,883: INFO: common: created directory at: artifacts]
[2025-03-24 19:12:11,883: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-24 19:12:11,883: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 19:12:25,609: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 19:12:25,940: INFO: stage_01_data_ingestion:  >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2025-03-24 19:12:29,292: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 19:12:29,610: INFO: stage_02_prepare_base_model: *******************]
[2025-03-24 19:12:29,610: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-24 19:12:29,611: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:12:29,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:12:29,611: INFO: common: created directory at: artifacts]
[2025-03-24 19:12:29,611: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-24 19:12:29,847: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-24 19:12:29,882: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 19:12:29,883: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 19:12:29,910: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-24 19:12:32,367: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 19:12:32,505: INFO: stage_03_model_training: *******************]
[2025-03-24 19:12:32,505: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-03-24 19:12:32,506: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:12:32,506: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:12:32,506: INFO: common: created directory at: artifacts]
[2025-03-24 19:12:32,506: INFO: common: created directory at: artifacts/training]
[2025-03-24 19:13:51,358: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-24 19:14:48,216: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 19:14:48,967: INFO: main:  >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-03-24 19:14:48,968: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:14:48,969: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:14:48,969: INFO: common: created directory at: artifacts]
[2025-03-24 19:14:48,969: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-24 19:14:48,969: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 19:14:54,863: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-24 19:14:55,188: INFO: main:  >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2025-03-24 19:14:55,188: INFO: main: *******************]
[2025-03-24 19:14:55,188: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-24 19:14:55,189: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:14:55,190: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:14:55,190: INFO: common: created directory at: artifacts]
[2025-03-24 19:14:55,190: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-24 19:14:55,397: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-24 19:14:55,439: WARNING: optimizer: At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 19:14:55,440: WARNING: __init__: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-03-24 19:14:55,470: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-24 19:14:55,470: INFO: main: *******************]
[2025-03-24 19:14:55,470: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-24 19:14:55,471: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:14:55,472: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:14:55,472: INFO: common: created directory at: artifacts]
[2025-03-24 19:14:55,472: INFO: common: created directory at: artifacts/training]
[2025-03-24 19:15:39,903: INFO: utils: NumExpr defaulting to 8 threads.]
[2025-03-24 19:15:40,605: INFO: stage_04_model_evaluation_with_mlflow: *******************]
[2025-03-24 19:15:40,605: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation Stage started <<<<<<]
[2025-03-24 19:15:40,606: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-24 19:15:40,606: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-24 19:15:40,607: INFO: common: created directory at: artifacts]
[2025-03-24 19:15:52,715: INFO: common: json file saved at: scores.json]
[2025-03-24 19:15:53,196: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-24 19:15:53,204: INFO: helpers: Accessing as NiteshNepal]
[2025-03-24 19:15:53,605: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/NiteshNepal/Kidney_Disease_Detection_Using_MLflow_DVC "HTTP/1.1 200 OK"]
[2025-03-24 19:15:54,321: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2025-03-24 19:15:54,326: INFO: helpers: Initialized MLflow to track repo "NiteshNepal/Kidney_Disease_Detection_Using_MLflow_DVC"]
[2025-03-24 19:15:54,326: INFO: helpers: Repository NiteshNepal/Kidney_Disease_Detection_Using_MLflow_DVC initialized!]
[2025-03-24 19:15:56,131: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 13). These functions will not be directly callable after loading.]
[2025-03-24 19:15:56,340: INFO: builder_impl: Assets written to: /var/folders/tq/_p_r2fsd4wnbps5lpj53z9q80000gn/T/tmpm8pm1brw/model/data/model/assets]
[2025-03-24 19:16:20,564: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation Stage completed <<<<<<

x==========x]
